Category.create(name: "nice animals")
Category.create(name: "mean animals")
Category.create(name: "best animals")
Category.create(name: "special animals")

Animal.create(name: "Bill", specie: "Dog", category_id: 1)
Animal.create(name: "Larry", specie: "Bunny", category_id: 1)
Animal.create(name: "Scarface", specie: "Lion", category_id: 2)
Animal.create(name: "Symba", specie: "Lion", category_id: 3)
Animal.create(name: "Hilary", specie: "Unicorn", category_id: 4)